{
 "title": "Philips HealthSuite FDM Services Dashboard",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[3m]))"
    }
   ]
  },
  {
   "title": "Total Threads on Containers ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(process_num_threads)" }
   ]
  },
  {
   "title": "In progress HTTP Requests",
   "type": "singlestat",
   "description": "Total number of requests in progress (Sum of all the requests in progress)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node_exporter:9011\"} - node_memory_MemAvailable_bytes{instance=\"node_exporter:9011\"}) / node_memory_MemTotal_bytes{instance=\"node_exporter:9011\"}) * 100"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "node_load1 / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "targets": [
    { "labelSelector": "*", "legendFormat": "{{ summary }}", "target": "Query", "type": "table" },
    { "labelSelector": "*", "legendFormat": "{{ instance }}", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Down Node",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"InstanceDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Request received per second (GET)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{method=\"GET\",action=\"\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{code=\"200\",method=\"GET\",controller=\"\",action=\"\"}) - sum(http_request_duration_seconds_bucket{code=\"200\",method=\"GET\",controller=\"\",action=\"\",le=\"+Inf\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(http_requests_received_total{code=\"200\",method=\"GET\",controller=\"\",action=\"\"})",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])\r / \rrate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 32 },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}