apiVersion: 1

datasources:
 - name: Prometheus AlertManager
   type: camptocamp-prometheus-alertmanager-datasource
   access: proxy
   org_id: 1
   url: http://alertmanager:9014
   version: 1
   editable: false
   json_data:
     severity_critical: 4
     severity_high: 3
     severity_warning: 2
     severity_info: 1
     
 - name: Loki
   type: loki
   access: proxy
   orgId: 1
   url: http://loki:3100
   isDefault: false
   version: 1
   editable: true     